services:
  - type: web
    name: smart-reservation-api
    env: docker
    plan: free
    dockerfilePath: "./Dockerfile"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
      - key: JDBC_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
