services:
  - type: web
    name: smart-reservation-api
    env: java
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: JAVA_VERSION
        value: "17"
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
      - key: JDBC_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
